### ISSUE TITLE
Error in console.status, 'Console' object has no attribute 'status'. 

### ISSUE THREAD

**Issue by HadiElnemr** [aboueleyes/cms-scrapper#3]
Python 3.9.4, the lines which contained `with console.status` raise 'Console' object has no attribute 'status' error. Works fine after commenting them.

**Comment by aboueleyes** [comment]
can you try updating rich?
```bash
> sudo pip3 install --upgrade rich
```

**Comment by HadiElnemr** [comment]
Upgraded rich, still _didn't_ work.

**Comment by aboueleyes** [comment]
can you please run
```bash
pip freeze | grep rich
```

**Comment by aboueleyes** [comment]
Packages conflict. use separate venv.
